#!/bin/sh

echo "h3. Active requirements and tasks"
echo
jira_version_report ACCRWF 'Project 0015' -r management stage1 incomplete postponed
echo
echo "h3. Postponed requirements and tasks"
echo
jira_version_report ACCRWF 'Project 0015' -k postponed
